src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from core.views import PageNotFoundView

urlpatterns = [
    path('', include("core.urls")),
    path('admin/', admin.site.urls),
    path('teachers/', include("teachers.urls")),
    path('groups/', include("groups.urls")),
    path('students/', include("students.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

handler404 = PageNotFoundView.as_view()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from core.views import IndexView, Login, Logout, Registration, EmailSend, ActivateUser, ProfileView

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("send-email/", EmailSend.as_view(), name="send-email"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("profile/", ProfileView.as_view(), name="user_profile")

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/groups/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from groups.views import GetAllGroupsView, CreateGroupView, UpdateGroupView, DeleteGroupView

app_name = "groups"

urlpatterns = [
    path("", GetAllGroupsView.as_view(), name="all_groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/students/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from students.views import GetAllStudentsView, CreateStudentView, UpdateStudentView, DeleteStudentView

app_name = "students"

urlpatterns = [
    path("", GetAllStudentsView.as_view(), name="all_students"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<int:pk>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<int:pk>/", DeleteStudentView.as_view(), name="delete_student"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/teachers/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path


from teachers.views import GetAllTeachersView, CreateTeacherView, UpdateTeacherView, DeleteTeacherView

app_name = "teachers"

urlpatterns = [
    path("", GetAllTeachersView.as_view(), name="all_teachers"),
    path("create/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update/<int:pk>/", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<int:pk>/", DeleteTeacherView.as_view(), name="delete_teacher"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/confirm_delete.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em; align-content:center; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <header>
                Are you sure you want to delete?
            </header>
            <button type="submit" class="btn btn-danger" value="Yes">Delete
            </button>
            <td><a type="button" class="btn btn-primary"
                       href="{% url "index" %}">No</a>
            </td>

        </form>
    </div>


{% endblock content %}

src/templates/email_sending.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em; align-content:center; margin: auto;" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Send">Send
            </button>
        </form>
    </div>


{% endblock content %}

src/templates/groups_list.html
{% extends "index.html" %}

{% block content %}

    <table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">URL</th>
      <th scope="col">Creation date</th>
      <th scope="col">Job</th>
      <th scope="col">Color</th>
      <th scope="col">Genre</th>
      <th scope="col">Card</th>


    </tr>
  </thead>
  <tbody>
   {% for group in groups %}
    <tr>
      <th scope="row">{{ group.pk }}</th>
      <td>{{ group.url }}</td>
      <td>{{ group.creation_date }}</td>
      <td>{{ group.group_job_name }}</td>
      <td>{{ group.group_color }}</td>
      <td>{{ group.favorite_genre }}</td>
      <td>{{ group.card_number }}</td>
      <td><a type="button" class="btn btn-secondary"
          href="{% url "groups:update_group" group.pk %}">Edit</a>
      </td>
      <td><a type="button" class="btn btn-danger"
          href="{% url "groups:delete_group" group.pk %}">Delete</a>
      </td>

    </tr>
   {% endfor %}
  </tbody>
</table>

{% endblock content %}

src/templates/index.html
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Cover Template · Bootstrap v5.2</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/cover/">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center text-bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0">LMS</h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link fw-bold py-1 px-0 active" style="margin-right: 5px" aria-current="page"
                   href="{% url "core:index" %}">Home</a>
                <a class="nav-link fw-bold py-1 px-0" style="margin-right: 5px"
                   href="{% url "students:all_students" %}">Students</a>
                <a class="nav-link fw-bold py-1 px-0" style="margin-right: 5px"
                   href="{% url "teachers:all_teachers" %}">Teachers</a>
                <a class="nav-link fw-bold py-1 px-0" style="margin-right: 20px"
                   href="{% url "groups:all_groups" %}">Groups</a>
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown"
                   aria-expanded="false">
                    <img src="https://github.com/mdo.png" alt="mdo" class="rounded-circle" width="32" height="32">
                </a>
                {% if user.is_authenticated %}
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="">{{ user.phone_number|title }}</a></li>
                        <li><a class="dropdown-item" href="">{{ user.email }}</a></li>
                        <li><a class="dropdown-item" href="{% url 'core:user_profile' %}">Profile</a></li>
                        {% if user.is_staff %}
                          <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin Page</a></li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Change password</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'core:logout' %}">Logout</a></li>
                    </ul>

                {% else %}
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="{% url 'core:login' %}">Login</a></li>
                        <li><a class="dropdown-item" href="{% url 'core:registration' %}">Registration</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Reset password</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'social:begin' 'github' %}">Github</a></li>
                        <li><a class="dropdown-item" href="{% url 'social:begin' 'steam' %}">Steam</a></li>
                    </ul>
                {% endif %}
            </nav>
        </div>
    </header>

    <main class="px-3">
        {% block content %}
            <h1>Welcome to our science little place!</h1>
            <p> {% load static %} <img src="{% static "img/for_front.jpg" %}" alt="Try again" width="800"
                                       height=640"/></p>
            <p class="lead">You can observe our current available students, teachers and groups.</p>
        {% endblock content %}
    </main>

    <footer class="mt-auto text-white-50">
        <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a
                href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
    </footer>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
</body>
</html>

src/templates/object_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}


{% block content %}
        {% if user.is_authenticated %}
    <div>
        <form method="POST" style="width: 25em; align-content:center; margin: auto;" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Create">Create
            </button>
        </form>
    </div>
        {% else %}
                    <h1>To get into site, please, login.</h1>
            <a type="button" class="btn btn-info"
                  href="{% url "core:login"%}">Login</a>

        {% endif %}

{% endblock content %}

src/templates/object_update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em; align-content:center; margin: auto;" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Update">Update
            </button>
        </form>
    </div>


{% endblock content %}

src/templates/students_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em;
         align-content: center
         ; margin: auto;">
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Create">Create
            </button>
        </form>
    </div>
{% endblock content %}

src/templates/students_list.html
{% extends "index.html" %}

{% block content %}

    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Avatar</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Birth date</th>
            <th scope="col">Age</th>
            <th scope="col">Grade</th>
            <th scope="col">Resume</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
        {% for student in students %}
            <tr>
                <td><img src="{{MEDIA_URL}}{{ student.avatar }}" alt="Try again" width="100"
                                       height=100"/> </td>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                {% if student.birth_date %}
                    <td>{{ student.birth_date }}</td>
                    <td>{{ student.age }}</td>
                {% else %}
                    <td>Undefined</td>
                    <td>Undefined</td>
                {% endif %}
                <td>{{ student.grade }}</td>
                {% if student.resume %}
                    <td><a type="button" class="btn btn-secondary"
                           href="{{MEDIA_URL}}{{ student.resume }}" download> Resume </a></td>
                {% else %}
                    <td>No resume </td>
                {% endif %}
                <td><a type="button" class="btn btn-warning"
                       href="{% url 'students:update_student' student.pk %}">Edit</a>
                </td>
                <td><a type="button" class="btn btn-danger"
                       href="{% url 'students:delete_student' student.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}

src/templates/teachers_list.html
{% extends "index.html" %}

{% block content %}

    <table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Avatar</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Email</th>
      <th scope="col">Address</th>
      <th scope="col">SSN</th>
      <th scope="col">Phone</th>
      <th scope="col">Birth date</th>
      <th scope="col">Group</th>

    </tr>
  </thead>
  <tbody>
   {% for teacher in teachers %}
    <tr>
      <td><img src="{{MEDIA_URL}}{{teacher.avatar}}" alt="Try again" width="100"
                                       height=100"/> </td>
      <td>{{ teacher.first_name }}</td>
      <td>{{ teacher.last_name }}</td>
      <td>{{ teacher.email }}</td>
      <td>{{ teacher.address }}</td>
      <td>{{ teacher.ssn }}</td>
      <td>{{ teacher.phone_number }}</td>
      <td>{{ teacher.birth_date }}</td>
      <td>
          {% for group in teacher.group.all %}
            <a type="button" class="btn btn-info"
          href="{% url "groups:update_group" group.pk %}">{{ group.url }}</a>
              {% endfor %}
              </td>
      <td><a type="button" class="btn btn-secondary"
          href="{% url "teachers:update_teacher" teacher.pk %}">Edit</a>
      </td>
      <td><a type="button" class="btn btn-danger"
          href="{% url "teachers:delete_teacher" teacher.pk %}">Delete</a>
      </td>

    </tr>
   {% endfor %}
  </tbody>
</table>

{% endblock content %}

src/templates/user_profile.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em; align-content:center; margin: auto;" enctype="multipart/form-data">
            {% csrf_token %}
            <img src="{{MEDIA_URL}}{{profile.photo}}" alt="Try again" width="100"
                                       height=100"/>
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Update" style="margin-top: 15px">Update
            </button>
        </form>
    </div>


{% endblock content %}